--CREATING A TABLE
--CREATE TABLE TABLE_NAME
CREATE TABLE Player(
--  COLUMN_NAME TYPE REQUIRED
    ID INTEGER NOT NULL,
    Name VARCHAR(255) NOT NULL,
    Age INTEGER NOT NULL,
    Nationality VARCHAR(30) NOT NULL,
    DOB TIMESTAMP,
    Designation INTEGER,
    -- UNIQUE KEY FOR THE TABLE
    PRIMARY KEY(ID)
);
